### ISSUE TITLE
v2: [mail] Доработка системы рассылки

### ISSUE THREAD

**Issue by ivan-varyukhin** [Medical-Information/medical-information-backend#145]

**Comment by ivan-varyukhin** [comment]
Рассылка производится подписавшимся пользователям.
Предусмотреть возможность подписки/отписки через личный кабинет и в письмах (?)

**Comment by StAndUP-ru** [comment]
действия на фронте: user поставил галку в ЛК, что подписан - post запрос на /users/subscriber/
действия в тылу: подписчикам рассылаются раз в неделю статьи (title + url), выбранные админом
