### ISSUE TITLE
v3: валидатор для проверки картинок (статья, аватар) на соответствие размерам и типам файла

### ISSUE THREAD

**Issue by ivan-varyukhin** [Medical-Information/medical-information-backend#250]

**Comment by AlexanderUp** [comment]
Аватар (либо инициалы), размер аватарки порядка 200х200 пикселей, 200кб.
Фотография (размер максимальный 1,5 mb, форматы jpg, .jpeg, .png)
(source: обсуждение в телеге)

**Comment by AlexanderUp** [comment]
Аватарка - не больше 500*500 и 200_000 байт

**Comment by elrouss** [comment]
Для аватара я тоже выставил форматы jpg, .jpeg, .png
