### ISSUE TITLE
[mail] Рассылка v.1: рассылка формируется администратором "вручную"

### ISSUE THREAD

**Issue by ivan-varyukhin** [Medical-Information/medical-information-backend#31]

**Comment by StAndUP-ru** [comment]
Планирую использовать связку Celery + Radis + Flower
Функционал:
1. Еженедельная рассылка статьей по подписке на врача
2. Уведомление о регистрации / смене пароля

**Comment by ivan-varyukhin** [comment]
"пока на данном этапе, подписка это просто email-рассылка (которая руками формируется), а что внутри будет уже неважно хоть новости, хоть статьи, хоть и то и другое, всё равно руками делается)"
остальное сносим в v.2

**Comment by ivan-varyukhin** [comment]
из текущего обсуждения: в случае успешной подписки возвращать соответствующее сообщение, также нужно учесть возврат ошибки в случае, если человек уже подписан
