### ISSUE TITLE
[user] Создать модель User

### ISSUE THREAD

**Issue by ivan-varyukhin** [Medical-Information/medical-information-backend#4]
Поля:
-Email
-Пароль
-Имя
-Фамилия
-статус доступа

**Comment by GritsenkoSerge** [comment]
Из перечисленного выше почти все есть в AbstractUser
Вижу себе так:
- наследуем от AbstractUser
- переопределяем id (миксин)
- добавляем is_moderator
- добавляем created_at, modified_at (миксин)
- можно убрать date_joined (date_joined = None), так как по сути это created_at
