### ISSUE TITLE
ci|cd

### ISSUE THREAD

**Issue by ArtemGrr** [Medical-Information/medical-information-backend#77]
- Вместо запуска проверки линтеров и тестов для каждой версии Python отдельно, можно использовать возможности многопоточности в GitHub Actions. Это позволит выполнять проверку параллельно для нескольких версий Python, что ускорит процесс и сократит время выполнения воркфлоу.
- Можно настроить кэширование папок с зависимостями, что позволяет переиспользовать предыдущие установки и уменьшить время, затрачиваемое на установку зависимостей. Также это ускорит сборку образа, если изменений в зависимостях не производилось.
- Разделение линтеров и запуска тестов в отдельные джобы упростит отслеживание проблем. Кроме того, если одна из задач не проходит, это не остановит выполнение других задач.
- Советую еще требовать проверки (ревью) Pull Request перед развертыванием изменений.

**Comment by GritsenkoSerge** [comment]
1. Добавил кэширование pip
2. В матрицу стратегий вынес названия линтеров. Теперь параллельно запускается 4 задания: ("3.10", "3.11") x ("flake8", "mypy")
3. Не понял о чем речь. Они изначально были разделены. Или это про фронтовый воркфлоу?
4. Изначально так и настроили. Минимум 2 ревью на PR. 
<img width="591" alt="image" src="https://github.com/Medical-Information/medical-information-backend/assets/105641816/5a53ec27-3104-41fe-ac73-95dd996827aa">
